### PR TITLE
Romea

### PR DESCRIPTION
**Pull request by jlaneurit**
Hello, i have made some changes in order to use our old mti xsens and our xsens mti 630.

### CODE REVIEW

**Comment by simonpierredeschenes** [comment]
Hi @jlaneurit, thank you for your contribution, this is very appreciated! I was wondering why you transposed the rotation matrix in the fill_from_Orientation_Data method. What was the transformation given by the original code? Was it a rotation matrix that represents the transformation from the global frame to the IMU frame or its inverse?

**Comment by peci1** [comment]
I was checking the manual for this part when I did the noetic PR, and the manual was extremely vague about this output. So I'm not sure if anybody actually used these outputs before...

**Comment by jlaneurit** [comment]
There is no transposition in the original code. For us,  when we used transposed matrix we get  the transformation from the global frame to the IMU frame and the results are the same as when using quaternions. Perhaps its depends of imu configuration can you check with your sensors ?

**Comment by simonpierredeschenes** [comment]
Thank you for your input @jlaneurit and @peci1. Everything looks good then, I will merge right now. Thank you again for your contribution @jlaneurit!

**Pull request merged**
